/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as CreationRouteRouteImport } from './routes/_creation/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as MainPrivacyRouteImport } from './routes/_main/privacy'
import { Route as PublishVRouteRouteImport } from './routes/_publish/v/route'
import { Route as CreationCreateIndexRouteImport } from './routes/_creation/create/index'
import { Route as PublishVPersonaRouteImport } from './routes/_publish/v/$persona'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationRouteRoute = CreationRouteRouteImport.update({
  id: '/_creation',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRouteRoute,
} as any)
const PublishVRouteRoute = PublishVRouteRouteImport.update({
  id: '/_publish/v',
  path: '/v',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationCreateIndexRoute = CreationCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => CreationRouteRoute,
} as any)
const PublishVPersonaRoute = PublishVPersonaRouteImport.update({
  id: '/$persona',
  path: '/$persona',
  getParentRoute: () => PublishVRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v': typeof PublishVRouteRouteWithChildren
  '/privacy': typeof MainPrivacyRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/v/$persona': typeof PublishVPersonaRoute
  '/create/': typeof CreationCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v': typeof PublishVRouteRouteWithChildren
  '/privacy': typeof MainPrivacyRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/v/$persona': typeof PublishVPersonaRoute
  '/create': typeof CreationCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_creation': typeof CreationRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_publish/v': typeof PublishVRouteRouteWithChildren
  '/_main/privacy': typeof MainPrivacyRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/_main/': typeof MainIndexRoute
  '/_publish/v/$persona': typeof PublishVPersonaRoute
  '/_creation/create/': typeof CreationCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/v'
    | '/privacy'
    | '/api/upload-image'
    | '/v/$persona'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/v'
    | '/privacy'
    | '/api/upload-image'
    | '/v/$persona'
    | '/create'
  id:
    | '__root__'
    | '/_creation'
    | '/_main'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_publish/v'
    | '/_main/privacy'
    | '/api/upload-image'
    | '/_main/'
    | '/_publish/v/$persona'
    | '/_creation/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CreationRouteRoute: typeof CreationRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PublishVRouteRoute: typeof PublishVRouteRouteWithChildren
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_creation': {
      id: '/_creation'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CreationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/privacy': {
      id: '/_main/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainPrivacyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_publish/v': {
      id: '/_publish/v'
      path: '/v'
      fullPath: '/v'
      preLoaderRoute: typeof PublishVRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_creation/create/': {
      id: '/_creation/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreationCreateIndexRouteImport
      parentRoute: typeof CreationRouteRoute
    }
    '/_publish/v/$persona': {
      id: '/_publish/v/$persona'
      path: '/$persona'
      fullPath: '/v/$persona'
      preLoaderRoute: typeof PublishVPersonaRouteImport
      parentRoute: typeof PublishVRouteRoute
    }
  }
}

interface CreationRouteRouteChildren {
  CreationCreateIndexRoute: typeof CreationCreateIndexRoute
}

const CreationRouteRouteChildren: CreationRouteRouteChildren = {
  CreationCreateIndexRoute: CreationCreateIndexRoute,
}

const CreationRouteRouteWithChildren = CreationRouteRoute._addFileChildren(
  CreationRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainPrivacyRoute: MainPrivacyRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface PublishVRouteRouteChildren {
  PublishVPersonaRoute: typeof PublishVPersonaRoute
}

const PublishVRouteRouteChildren: PublishVRouteRouteChildren = {
  PublishVPersonaRoute: PublishVPersonaRoute,
}

const PublishVRouteRouteWithChildren = PublishVRouteRoute._addFileChildren(
  PublishVRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CreationRouteRoute: CreationRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PublishVRouteRoute: PublishVRouteRouteWithChildren,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
