/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VRouteRouteImport } from './routes/v/route'
import { Route as PreviewRouteRouteImport } from './routes/preview/route'
import { Route as CreateRouteRouteImport } from './routes/create/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as VPersonaRouteImport } from './routes/v/$persona'
import { Route as PreviewPersonaRouteImport } from './routes/preview/$persona'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'

const VRouteRoute = VRouteRouteImport.update({
  id: '/v',
  path: '/v',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRouteRoute = PreviewRouteRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRouteRoute = CreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRouteRoute,
} as any)
const VPersonaRoute = VPersonaRouteImport.update({
  id: '/$persona',
  path: '/$persona',
  getParentRoute: () => VRouteRoute,
} as any)
const PreviewPersonaRoute = PreviewPersonaRouteImport.update({
  id: '/$persona',
  path: '/$persona',
  getParentRoute: () => PreviewRouteRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteRouteWithChildren
  '/preview': typeof PreviewRouteRouteWithChildren
  '/v': typeof VRouteRouteWithChildren
  '/api/upload-image': typeof ApiUploadImageRoute
  '/preview/$persona': typeof PreviewPersonaRoute
  '/v/$persona': typeof VPersonaRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRouteRouteWithChildren
  '/v': typeof VRouteRouteWithChildren
  '/api/upload-image': typeof ApiUploadImageRoute
  '/preview/$persona': typeof PreviewPersonaRoute
  '/v/$persona': typeof VPersonaRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteRouteWithChildren
  '/preview': typeof PreviewRouteRouteWithChildren
  '/v': typeof VRouteRouteWithChildren
  '/api/upload-image': typeof ApiUploadImageRoute
  '/preview/$persona': typeof PreviewPersonaRoute
  '/v/$persona': typeof VPersonaRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/preview'
    | '/v'
    | '/api/upload-image'
    | '/preview/$persona'
    | '/v/$persona'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/v'
    | '/api/upload-image'
    | '/preview/$persona'
    | '/v/$persona'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/preview'
    | '/v'
    | '/api/upload-image'
    | '/preview/$persona'
    | '/v/$persona'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRouteRoute: typeof CreateRouteRouteWithChildren
  PreviewRouteRoute: typeof PreviewRouteRouteWithChildren
  VRouteRoute: typeof VRouteRouteWithChildren
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v': {
      id: '/v'
      path: '/v'
      fullPath: '/v'
      preLoaderRoute: typeof VRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRouteRoute
    }
    '/v/$persona': {
      id: '/v/$persona'
      path: '/$persona'
      fullPath: '/v/$persona'
      preLoaderRoute: typeof VPersonaRouteImport
      parentRoute: typeof VRouteRoute
    }
    '/preview/$persona': {
      id: '/preview/$persona'
      path: '/$persona'
      fullPath: '/preview/$persona'
      preLoaderRoute: typeof PreviewPersonaRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CreateRouteRouteChildren {
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteRouteChildren: CreateRouteRouteChildren = {
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteRouteWithChildren = CreateRouteRoute._addFileChildren(
  CreateRouteRouteChildren,
)

interface PreviewRouteRouteChildren {
  PreviewPersonaRoute: typeof PreviewPersonaRoute
}

const PreviewRouteRouteChildren: PreviewRouteRouteChildren = {
  PreviewPersonaRoute: PreviewPersonaRoute,
}

const PreviewRouteRouteWithChildren = PreviewRouteRoute._addFileChildren(
  PreviewRouteRouteChildren,
)

interface VRouteRouteChildren {
  VPersonaRoute: typeof VPersonaRoute
}

const VRouteRouteChildren: VRouteRouteChildren = {
  VPersonaRoute: VPersonaRoute,
}

const VRouteRouteWithChildren =
  VRouteRoute._addFileChildren(VRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRouteRoute: CreateRouteRouteWithChildren,
  PreviewRouteRoute: PreviewRouteRouteWithChildren,
  VRouteRoute: VRouteRouteWithChildren,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
